#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# If the control reaches this step, the service can be enabled and started

touch uptime-kuma.env

systemctl --user enable uptime-kuma.service
systemctl --user restart uptime-kuma.service uptime-kuma-mariadb.service uptime-kuma-app.service
