#
# Restic include patterns for the module backup
# Syntax reference: https://pkg.go.dev/path/filepath#Glob
# Restic --files-from: https://restic.readthedocs.io/en/stable/040_backup.html#including-files
#

volumes/kuma-data
state/kuma.env
state/database.env
state/kuma.sql
