#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "host": os.environ["TRAEFIK_HOST"],
    "lets_encrypt": os.environ.get("TRAEFIK_LETS_ENCRYPT") == "True",
    "smtp_enabled": os.environ.get("SMTP_ENABLED") == "True",
    "notification_emails": [e for e in os.environ.get("NOTIFICATION_EMAILS", "").split(",") if e],
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
