#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import secrets
import agent

os.umask(0o077)

agent.write_envfile("database.env", {
    "MARIADB_ROOT_PASSWORD": secrets.token_hex(16),
    "MARIADB_DATABASE": "uptime-kuma",
    "MARIADB_USER": "uptime-kuma",
    "MARIADB_PASSWORD": secrets.token_hex(16),
})
