#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

exec 1>&2

# sync-smarthost waits for the server, and skips if the module is stopped
if systemctl --user -q is-enabled kuma.service; then
    sync-smarthost
fi
