#!/bin/bash

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

exec 1>&2

# Instances created before the MariaDB container need the Uptime Kuma DB variables
write-kuma-db-env
