#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

touch uptime-kuma.env

systemctl --user try-restart uptime-kuma.service uptime-kuma-mariadb.service uptime-kuma-app.service
