#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "TRAEFIK_HOST",
    ]:
    agent.set_env(evar, original_environment[evar])

agent.set_env("TRAEFIK_LETS_ENCRYPT", original_environment.get("TRAEFIK_LETS_ENCRYPT", "False"))
agent.set_env("SMTP_ENABLED", original_environment.get("SMTP_ENABLED", "False"))
agent.set_env("NOTIFICATION_EMAILS", original_environment.get("NOTIFICATION_EMAILS", ""))

agent.dump_env()
