#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

request = json.load(sys.stdin)
renv = request['environment']

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "host": renv["TRAEFIK_HOST"],
    "lets_encrypt": renv.get("TRAEFIK_LETS_ENCRYPT") == "True",
    "smtp_enabled": renv.get("SMTP_ENABLED") == "True",
    "notification_emails": [e for e in renv.get("NOTIFICATION_EMAILS", "").split(",") if e],
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
